### ISSUE TITLE
Having issues getting started.

### ISSUE THREAD

**Issue by Pome-ro** [an-dr/Env#4] opened 2023-05-03 14:13 UTC
Maybe I'm using this wrong. But I can't get it to enable an environment I've created unless I use the `Enable-Environment` command with no params. 

I'm not sure if this is a failing in expectations of use, or failings in the code itself. 

```shell
 PS > New-Environment -Name testenv

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            5/3/2023  9:53 AM                testenv
```

So far so good. 

```shell
PS > dir

    Directory: C:\Code\Sandbox

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            5/3/2023  9:53 AM                testenv
```

I can see the dir.

```powershell
PS > Enable-Environment testenv
[ERROR] No environment found
PS > Enable-Environment -path .\testenv\
[ERROR] No environment found
PS > Enable-Environment -path .\
[ERROR] No environment found
PS >Enable-Environment
[INFO] Selected: C:\Code\Sandbox\testenv
[INFO] Enabling environment: C:\Code\Sandbox\testenv
[DONE] Environment testenv is enabled.
PS > test-DirIsEnv -Dir .\testenv\
False
```

I see that Enable-Environment has a Path param, but it doesn't seem to be working as I expect it to. Feeding it a path to the environment folder doesn't result in enabling the environment, same with the root directory. Not shown above, but I've also tried the full path instead of using .\ and I've tried pointing it directly at the .psm1 file in the folder.

**Comment by an-dr** [comment] 2023-05-03 16:52
I managed to reproduce it. It is happening on Windows Powershell 5. It's a compatibility bug that I missed because I developed it on pwsh 7. 

Thanks for the reporting, I'll fix it in the next version and let you know.

**Comment by an-dr** [comment] 2023-05-03 17:49
Try the last version, it should be fixed
```
Update-Module -Name Env -RequiredVersion 2.1.2
```

**Comment by Pome-ro** [comment] 2023-05-03 18:21
Yup just tested this, looks like that resolved it!

**Closed as completed** 2023-05-03 18:21 UTC
Labels: bug
